# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/trusty64"
  end
  
  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/trusty64"
  end
  
end
